In [1]:
import numpy as np


In [2]:
def fib_dynamic_iteritive(n):
    arr= np.array([0,0,1],dtype=np.int64)
    if (n  ==0) :
        return arr[n+1]
    else:
        for i in range(1,n):
            arr = np.roll(arr,2)
            arr[2] = arr[:2].sum()
        return arr[2]       
fib_dynamic_iteritive(1000)        
    

817770325994397771

In [3]:
def fib_dynamic_recursive(n,idx=1,arr=[0,0,1]):
    arr =np.array(arr,dtype =np.int64)
    if (n ==idx) :
        return arr[2]
    elif(n < 2):
        return arr[n+1]
    else:
        arr = np.roll(arr,2)
        arr[2] = arr[:2].sum()
        return fib_dynamic_recursive(n,idx+1,arr) 
fib_dynamic_recursive(4)

3

In [44]:
def DynamicknapsackItr(weights,valus,bagWeight):
    rows= len(valus)+1
    cols = bagWeight+1
    profitmat= np.zeros((rows,cols))
    
    for v in range(1,rows):
        
        for w in range(3,cols):
            
            if (w-weights[v-1])<0:
                  profitmat[v,w]=(profitmat[v-1][w])
            else:
                  profitmat[v,w]=(max(profitmat[v-1,w],profitmat[v-1,w-weights[v-1]]+valus[v-1]))
            
    print(profitmat)
items =[3,4,6,5] 
valus =[2,3,1,4]
DynamicknapsackItr(items,valus,8)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 2. 2. 2. 2. 2.]
 [0. 0. 0. 2. 3. 3. 3. 5. 5.]
 [0. 0. 0. 2. 3. 3. 3. 5. 5.]
 [0. 0. 0. 2. 3. 4. 4. 5. 6.]]
